# Changes here will be overwritten by Copier
_commit: v0.3.5
_src_path: https://gitlab.softwareheritage.org/swh/devel/swh-py-template.git
description: Software Heritage lister
distribution_name: swh-lister
have_cli: true
have_workers: true
package_root: swh/lister
project_name: swh.lister
python_minimal_version: '3.9'
readme_format: rst
