# RPM lister parameters to process openSUSE source packages

url: http://opensuse.org
instance: openSUSE
rpm_src_data:
  - base_url: http://download.opensuse.org/source/
    releases:
      - tumbleweed
      - jump/15.2
      - leap/15.0-Current
      - leap/15.0
      - leap/15.1
      - leap/15.2
      - leap/15.3
      - leap/15.4
      - leap/15.5
      - leap/42.2
      - leap/42.3-Current
      - leap/42.3
    components:
      - oss
      - non-oss
    index_url_templates:
      - $base_url/distribution/$release/repo/$component/
      - $base_url/distribution/$release/repo/$component/suse/
      - $base_url/$release/repo/$component/
